### ISSUE TITLE
Suggestion: Support for async retrieval on DataRetrieverRouter

### ISSUE THREAD

**Issue by ovaillancourt** [franciscogouveia/rbac-core#13]
Since the `evaluatePolicy` method is asynchronous, it seems like it would be feasible to add the option of registering an asynchronous retriever in the `DataRetrievalRouter`, this would offer the capability of doing more complex verifications (for example verifications that require calls to another system).

Use case example: A policy that gives access to a resource only if the caller is a friend of it's owner.

``` javascript

//Upon creation of the dataRetrieverRouter :
dataRetrieverRouter.register('relationships', (source, key, context, cb) => {
    //Hypothetical DB query that produces an array of friend identifiers
    if(key === 'friends'){
        db.relationships.findOne({
            user : context.caller.id
            type : 'friend'    
        },
        cb);
    }    
});

//Policy looks like this:
{
    apply : 'permit-overrides',
    rules : [
        {
            target : { 'relationships:friends' : '<resource owner id here>'},
            effect : 'permit'
        },
        {
            effect : 'deny'
        }
    ]
}
```

In order to make this backward compatible with the current interface, determining whether a registered retriever is synchronous or not could be done by checking the arity of the handler passed to the `.register` call or maybe by exposing a new `.registerAsync` call.

Thoughts?

**Comment by franciscogouveia** [comment]
I'm taking care of it.

Even though the `register` can be backwards compatible, `get` cannot. It will need a callback to always work.

**Comment by ovaillancourt** [comment]
Ah yeah good point, I forgot that `.get` was part of the public interface.

**Comment by franciscogouveia** [comment]
Should work now. This is a great feature :+1:
