### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by marsanla** [franciscogouveia/rbac-core#16]
Maybe its possible to use wildcards in targets... for example:

``` js
{
        target: [{'credentials:scope': 'admin:*'}],
        apply: 'deny-overrides',
        rules: [{
            effect: 'permit'
        }]
}
```

Using [https://www.npmjs.com/package/glob-to-regexp](https://www.npmjs.com/package/glob-to-regexp)

What do you think?

**Comment by franciscogouveia** [comment]
Maybe... I just wonder what would be the performance implications. I'm at the moment short on time, did you give it a try?

**Comment by moacirosa** [comment]
Do you guys have some idea about this topic? I'm facing some similar "issue".  I'd like to authorize /swaggerui* to everybody. Then it would be possible to expose `swagger` but protect the entire API by default. Does it make sense? I didn't find anything about Regex for example.

**Comment by franciscogouveia** [comment]
Version `2.1.0` released with support for RegExp.
For examples, check:
* https://github.com/franciscogouveia/rbac-core/commit/c203af4fc415c27675d391cad67253a9240bb93b
* https://github.com/franciscogouveia/rbac-core/commit/4fdbbc2f1e993ed9d179b507d3255159045ccc58

No new external dependencies, pure javascript RegExp.

Hope it helps. Sorry for taking so long (time is short).

**Comment by moacirosa** [comment]
Great Job! Thanks a lot!
